In [ ]:
import pandas as pd

In [ ]:
data = {
    "name": ["shabbir", "Hussain", "adam", "yousuf"],
    "age": [25, 23, 29, 27],
    "city": ["Karachi", "Lahore", "Karachi", "Islamabad"],
}

df = pd.DataFrame(data)
print(df)

      name  age       city
0  shabbir   25    Karachi
1  Hussain   23     Lahore
2     adam   29    Karachi
3   yousuf   27  Islamabad

In [ ]:
df[["age","name"]]

   age     name
0   25  shabbir
1   23  Hussain
2   29     adam
3   27   yousuf

In [ ]:
df.head()

      name  age       city
0  shabbir   25    Karachi
1  Hussain   23     Lahore
2     adam   29    Karachi
3   yousuf   27  Islamabad

In [ ]:
df.tail()

      name  age       city
0  shabbir   25    Karachi
1  Hussain   23     Lahore
2     adam   29    Karachi
3   yousuf   27  Islamabad

In [ ]:
df.shape

(4, 3)

In [ ]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [ ]:
df.dtypes

name    object
age      int64
city    object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

             age
count   4.000000
mean   26.000000
std     2.581989
min    23.000000
25%    24.500000
50%    26.000000
75%    27.500000
max    29.000000

In [ ]:
df = pd.read_csv("customers-1000.csv")

In [ ]:
df.shape

(1000, 12)

In [ ]:
df .head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [ ]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [ ]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   object
 2   First Name         1000 non-null   object
 3   Last Name          1000 non-null   object
 4   Company            1000 non-null   object
 5   City               1000 non-null   object
 6   Country            1000 non-null   object
 7   Phone 1            1000 non-null   object
 8   Phone 2            1000 non-null   object
 9   Email              1000 non-null   object
 10  Subscription Date  1000 non-null   object
 11  Website            1000 non-null   object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB

In [ ]:
df.describe()

             Index
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [ ]:
df.isna().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [ ]:
df["First Name"].nunique()

536

In [ ]:
df[df['Index'] <25]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
5,6,8aaa5d0CE9ee311,Marissa,Gamble,Cherry and Sons,Webertown,Sudan,001-645-334-5514x0786,(751)980-3163,katieallison@leonard.com,2021-11-17,http://www.kaufman.org/
6,7,73B22Ac8A43DD1A,Julie,Cooley,"Yu, Norman and Sharp",West Sandra,Japan,+1-675-243-7422x9177,(703)337-5903,priscilla88@stephens.info,2022-03-26,http://www.sexton-chang.com/
7,8,DC94CCd993D311b,Lauren,Villa,"French, Travis and Hensley",New Yolanda,Fiji,081.226.1797x647,186.540.9690x605,colehumphrey@austin-caldwell.com,2020-08-14,https://www.kerr.com/
8,9,9Ba746Cb790FED9,Emily,Bryant,"Moon, Strickland and Combs",East Normanchester,Seychelles,430-401-5228x35091,115-835-3840,buckyvonne@church-lutz.com,2020-12-30,http://grimes.com/
9,10,aAa1EDfaA70DA0c,Marie,Estrada,May Inc,Welchton,United Arab Emirates,001-648-790-9244,973-767-3611,christie44@mckenzie.biz,2020-09-03,https://www.salinas.net/
10,11,bf104C25d0BA4E1,Nichole,Cannon,Rios and Sons,West Devon,Burundi,0647787401,139.476.1068,blandry@henson-harris.biz,2021-04-26,http://www.humphrey.org/
11,12,bf2fA37cbAd7dDc,Bernard,Ritter,Bradford and Sons,West Francisco,Palau,292.313.1902,(065)075-0554,tammiepope@arroyo-baldwin.com,2022-01-19,http://sellers.biz/
12,13,4fa8ffcdBbf53bB,Darryl,Archer,Kerr-Cherry,Holtfurt,Uganda,(389)437-1716,092.364.7349x593,woodalejandro@skinner-sloan.biz,2022-04-18,https://www.daniels.com/
13,14,aBd960429ecd363,Ryan,Li,"Hooper, Cross and Holt",Batesville,Liechtenstein,001-119-787-0125x4500,001-477-254-3645,lmassey@duke.com,2021-03-06,http://nunez.com/
14,15,2a0c691Ce19C6f3,Vicki,Nunez,"Leonard, Galvan and Blackburn",Barbaraborough,Haiti,(217)474-0312,(098)195-0840x79579,zgrant@sweeney.com,2022-01-30,https://reynolds.com/
15,16,B58fecf82f997Dd,Sean,Townsend,Preston-Sosa,Velasquezberg,Iran,001-534-283-5153,5786415664,lkline@maxwell.info,2020-05-30,http://www.vargas.biz/
16,17,41d0201DcF028b5,Sophia,Mathis,Richard-Velasquez,Toddhaven,Switzerland,001-858-762-7896x916,274-147-4185x15182,brockmason@faulkner-may.com,2020-01-23,http://www.vaughn.com/
17,18,B1A1b09CD5C3b6a,Helen,Potts,"Rangel, Livingston and Patel",Douglasland,Seychelles,(140)862-2659,+1-875-299-7166,carrollmia@donovan-keith.com,2021-07-27,http://www.kennedy-edwards.biz/
18,19,ba5a73D210dCcE4,Joann,Finley,Harvey PLC,Barrettshire,Montserrat,(941)715-8720x950,155.433.4824x955,gabriela86@sampson.com,2022-04-11,http://www.harrell.com/
19,20,F6cD561cecdfA6d,Thomas,Walsh,Best-Thomas,Roblesport,Kiribati,679.326.0724,001-305-038-6009,timcoleman@frank-king.org,2020-09-11,http://www.kane.com/
20,21,dEb9310eec04a8D,Cristina,Lam,Watts-Allison,West Jocelynfort,Korea,4292705811,(086)253-7505x70576,charlotte16@hood-zhang.org,2020-01-04,http://whitehead.net/
21,22,ed3894D6DE7F711,Vicki,Heath,"Cherry, Schultz and Ruiz",Port Cameronbury,Bangladesh,(889)311-5580x6390,(260)437-9972,alan46@benjamin.com,2020-11-06,https://www.bird.com/
22,23,EFeFaC727F12CDF,Glenn,Wang,Warner-Hodge,West Rachael,Gabon,834.104.6424x8311,001-741-628-9295,anna80@mata.com,2022-01-01,http://brooks-kerr.com/
23,24,c5CB6C5bFB91fdC,Darius,Benitez,Giles LLC,Mejiashire,Jersey,+1-797-864-3151x25142,139-216-5379x6030,garrettdurham@olsen.com,2022-02-28,https://washington.com/

In [ ]:
df["Country"].nunique()

240

In [ ]:
df[df['Country'] == "Uganda"]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
12,13,4fa8ffcdBbf53bB,Darryl,Archer,Kerr-Cherry,Holtfurt,Uganda,(389)437-1716,092.364.7349x593,woodalejandro@skinner-sloan.biz,2022-04-18,https://www.daniels.com/
85,86,8799Bb0d0eF9F7b,Autumn,Choi,Bates LLC,Port Scott,Uganda,374-961-9091x6048,001-460-538-5514,varmstrong@braun.org,2020-12-07,http://www.fritz-galloway.com/
123,124,AAEfB9E5c86ab72,Shaun,Luna,"Sparks, Garcia and Maxwell",West Emma,Uganda,(092)989-4066,+1-641-277-2380x929,mshaw@cantu-le.net,2021-12-18,http://www.pennington.com/
158,159,57234838A0aD5F4,Don,Ho,Stark-Glover,Riosport,Uganda,426-986-3364,588.449.6684x0997,rwallace@shepherd-mcdowell.com,2022-02-12,https://www.ellison.com/
468,469,Af7F1daF5fFc3aa,Travis,Duran,"Vincent, Watson and Esparza",Port Russellmouth,Uganda,001-422-237-1259x85115,044-273-8508,rshields@mack.com,2021-07-23,http://wolfe.net/
592,593,D48fdcDF9d7A214,Lawrence,Campos,Pittman LLC,Heathfurt,Uganda,126-968-6585x449,852.589.3656x973,santosrussell@hicks.com,2022-02-09,https://russo.com/
640,641,eE3aabEcf63fb74,Olivia,Cross,Richard-Lutz,Rickburgh,Uganda,(834)478-1447,167-065-1626,alec41@stuart.net,2020-02-18,https://zhang.org/
851,852,89A9A525b79da34,Kelly,Bradshaw,"Horn, Sherman and Barry",West Raven,Uganda,(562)102-3959,738.554.5652x77218,tgill@novak-patton.com,2021-06-18,http://leach-carlson.net/

In [ ]:
df[(df['Index'] <25) & (df['Country'] == "Uganda")]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
12,13,4fa8ffcdBbf53bB,Darryl,Archer,Kerr-Cherry,Holtfurt,Uganda,(389)437-1716,092.364.7349x593,woodalejandro@skinner-sloan.biz,2022-04-18,https://www.daniels.com/

In [ ]:
df[(df['Index'] <25) | (df['Country'] == "Uganda")]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
5,6,8aaa5d0CE9ee311,Marissa,Gamble,Cherry and Sons,Webertown,Sudan,001-645-334-5514x0786,(751)980-3163,katieallison@leonard.com,2021-11-17,http://www.kaufman.org/
6,7,73B22Ac8A43DD1A,Julie,Cooley,"Yu, Norman and Sharp",West Sandra,Japan,+1-675-243-7422x9177,(703)337-5903,priscilla88@stephens.info,2022-03-26,http://www.sexton-chang.com/
7,8,DC94CCd993D311b,Lauren,Villa,"French, Travis and Hensley",New Yolanda,Fiji,081.226.1797x647,186.540.9690x605,colehumphrey@austin-caldwell.com,2020-08-14,https://www.kerr.com/
8,9,9Ba746Cb790FED9,Emily,Bryant,"Moon, Strickland and Combs",East Normanchester,Seychelles,430-401-5228x35091,115-835-3840,buckyvonne@church-lutz.com,2020-12-30,http://grimes.com/
9,10,aAa1EDfaA70DA0c,Marie,Estrada,May Inc,Welchton,United Arab Emirates,001-648-790-9244,973-767-3611,christie44@mckenzie.biz,2020-09-03,https://www.salinas.net/
10,11,bf104C25d0BA4E1,Nichole,Cannon,Rios and Sons,West Devon,Burundi,0647787401,139.476.1068,blandry@henson-harris.biz,2021-04-26,http://www.humphrey.org/
11,12,bf2fA37cbAd7dDc,Bernard,Ritter,Bradford and Sons,West Francisco,Palau,292.313.1902,(065)075-0554,tammiepope@arroyo-baldwin.com,2022-01-19,http://sellers.biz/
12,13,4fa8ffcdBbf53bB,Darryl,Archer,Kerr-Cherry,Holtfurt,Uganda,(389)437-1716,092.364.7349x593,woodalejandro@skinner-sloan.biz,2022-04-18,https://www.daniels.com/
13,14,aBd960429ecd363,Ryan,Li,"Hooper, Cross and Holt",Batesville,Liechtenstein,001-119-787-0125x4500,001-477-254-3645,lmassey@duke.com,2021-03-06,http://nunez.com/
14,15,2a0c691Ce19C6f3,Vicki,Nunez,"Leonard, Galvan and Blackburn",Barbaraborough,Haiti,(217)474-0312,(098)195-0840x79579,zgrant@sweeney.com,2022-01-30,https://reynolds.com/
15,16,B58fecf82f997Dd,Sean,Townsend,Preston-Sosa,Velasquezberg,Iran,001-534-283-5153,5786415664,lkline@maxwell.info,2020-05-30,http://www.vargas.biz/
16,17,41d0201DcF028b5,Sophia,Mathis,Richard-Velasquez,Toddhaven,Switzerland,001-858-762-7896x916,274-147-4185x15182,brockmason@faulkner-may.com,2020-01-23,http://www.vaughn.com/
17,18,B1A1b09CD5C3b6a,Helen,Potts,"Rangel, Livingston and Patel",Douglasland,Seychelles,(140)862-2659,+1-875-299-7166,carrollmia@donovan-keith.com,2021-07-27,http://www.kennedy-edwards.biz/
18,19,ba5a73D210dCcE4,Joann,Finley,Harvey PLC,Barrettshire,Montserrat,(941)715-8720x950,155.433.4824x955,gabriela86@sampson.com,2022-04-11,http://www.harrell.com/
19,20,F6cD561cecdfA6d,Thomas,Walsh,Best-Thomas,Roblesport,Kiribati,679.326.0724,001-305-038-6009,timcoleman@frank-king.org,2020-09-11,http://www.kane.com/
20,21,dEb9310eec04a8D,Cristina,Lam,Watts-Allison,West Jocelynfort,Korea,4292705811,(086)253-7505x70576,charlotte16@hood-zhang.org,2020-01-04,http://whitehead.net/
21,22,ed3894D6DE7F711,Vicki,Heath,"Cherry, Schultz and Ruiz",Port Cameronbury,Bangladesh,(889)311-5580x6390,(260)437-9972,alan46@benjamin.com,2020-11-06,https://www.bird.com/
22,23,EFeFaC727F12CDF,Glenn,Wang,Warner-Hodge,West Rachael,Gabon,834.104.6424x8311,001-741-628-9295,anna80@mata.com,2022-01-01,http://brooks-kerr.com/
23,24,c5CB6C5bFB91fdC,Darius,Benitez,Giles LLC,Mejiashire,Jersey,+1-797-864-3151x25142,139-216-5379x6030,garrettdurham@olsen.com,2022-02-28,https://washington.com/
85,86,8799Bb0d0eF9F7b,Autumn,Choi,Bates LLC,Port Scott,Uganda,374-961-9091x6048,001-460-538-5514,varmstrong@braun.org,2020-12-07,http://www.fritz-galloway.com/
123,124,AAEfB9E5c86ab72,Shaun,Luna,"Sparks, Garcia and Maxwell",West Emma,Uganda,(092)989-4066,+1-641-277-2380x929,mshaw@cantu-le.net,2021-12-18,http://www.pennington.com/
158,159,57234838A0aD5F4,Don,Ho,Stark-Glover,Riosport,Uganda,426-986-3364,588.449.6684x0997,rwallace@shepherd-mcdowell.com,2022-02-12,https://www.ellison.com/
468,469,Af7F1daF5fFc3aa,Travis,Duran,"Vincent, Watson and Esparza",Port Russellmouth,Uganda,001-422-237-1259x85115,044-273-8508,rshields@mack.com,2021-07-23,http://wolfe.net/
592,593,D48fdcDF9d7A214,Lawrence,Campos,Pittman LLC,Heathfurt,Uganda,126-968-6585x449,852.589.3656x973,santosrussell@hicks.com,2022-02-09,https://russo.com/
640,641,eE3aabEcf63fb74,Olivia,Cross,Richard-Lutz,Rickburgh,Uganda,(834)478-1447,167-065-1626,alec41@stuart.net,2020-02-18,https://zhang.org/
851,852,89A9A525b79da34,Kelly,Bradshaw,"Horn, Sherman and Barry",West Raven,Uganda,(562)102-3959,738.554.5652x77218,tgill@novak-patton.com,2021-06-18,http://leach-carlson.net/

In [ ]:
df.sort_index(ascending=False)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/

In [ ]:
df.sort_values(by="First Name")

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
255,256,cf01fCEFeABD468,Aaron,Potts,Berg-Cannon,Kathrynville,Bulgaria,508-464-4330x29848,234.844.2278,kathryn22@patel-gross.com,2021-05-21,http://www.burns-kane.com/
503,504,8f7B9864aF6B829,Abigail,Shah,Ortiz LLC,Mercadoland,Sierra Leone,3369249620,0410774981,ecollins@wise.biz,2022-03-11,https://www.cantrell.biz/
908,909,8e1C3eFE6EB28A5,Abigail,Cochran,"Valentine, Foster and Church",North Shannon,Switzerland,+1-015-330-3044x9291,001-994-735-7201,elijahcherry@mann.com,2020-03-01,http://larson.com/
560,561,fE90dD920AAA4bC,Adam,Shaffer,Diaz-Harrell,Garymouth,Tajikistan,543.138.1663x40499,001-291-430-6991x7025,isaiah33@ho-lane.com,2021-04-16,http://liu.com/
736,737,A7d0eb4f6Bb890f,Adam,Singh,Johns Group,Lake Mckenzieville,Bolivia,(201)217-5414x76650,685.645.5159,chandlerluis@forbes-dickson.org,2021-10-11,https://www.hodge.org/
...,...,...,...,...,...,...,...,...,...,...,...,...
793,794,aD0CaDFf8b23B92,Yvette,Mccoy,"Reeves, Harding and Bowman",East Monica,Morocco,1888274804,121.200.7243x299,aatkinson@suarez.biz,2021-03-14,https://www.wolfe.com/
125,126,5Cc3bd1D1d6BFd8,Yvonne,Jordan,"Oneal, Barker and Kaufman",South Caseyside,Timor-Leste,+1-587-011-4054,001-735-509-2475x253,mercedes83@gill.org,2020-10-23,https://www.cohen-king.org/
304,305,0eeC8874c3cfEE5,Zachary,Parker,Ewing and Sons,Port Glennborough,Burkina Faso,+1-844-254-1041x6556,814-409-3822,willie12@norris-pennington.com,2021-12-09,https://yoder.com/
825,826,afC5fBDC4FFFE8f,Zoe,Solomon,Meyers-Odonnell,Bettyland,Wallis and Futuna,711-700-7316,374.942.9026,angelicaarias@harmon-cabrera.info,2021-09-16,https://www.bender-church.org/
706,707,8b6d8b16D0C3b24,Zoe,Guerra,Hogan-Butler,North Bethanyhaven,Qatar,345.492.4217,(125)614-6475,cnewman@price-morrow.com,2021-05-04,https://berry.com/

In [ ]:
df.sort_values(['Index', 'First Name'],ascending=[False,True])

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/

In [ ]:
data = {
    "customer": ["A", "B", "C", "D", "E", "F"],
    "age": [22, 35, 29, 41, 25, 38],
    "plan": ["Free", "Pro", "Pro", "Free", "Pro", "Free"],
    "monthly_spend": [0, 50, 40, 0, 70, 10],
    "churn": [1, 0, 0, 1, 0, 1],
}

df = pd.DataFrame(data)

In [ ]:
print(df['churn'].sum())

3

In [ ]:
df['churn'].mean()

np.float64(0.5)

In [ ]:
df[df['monthly_spend'] > 30 ]

  customer  age plan  monthly_spend  churn
1        B   35  Pro             50      0
2        C   29  Pro             40      0
4        E   25  Pro             70      0

In [ ]:
df[df['plan'] == "Pro"]

  customer  age plan  monthly_spend  churn
1        B   35  Pro             50      0
2        C   29  Pro             40      0
4        E   25  Pro             70      0

In [ ]:
df.sort_values("monthly_spend",ascending=False)

  customer  age  plan  monthly_spend  churn
4        E   25   Pro             70      0
1        B   35   Pro             50      0
2        C   29   Pro             40      0
5        F   38  Free             10      1
0        A   22  Free              0      1
3        D   41  Free              0      1

In [ ]:
df[(df['plan'] == "Free") & (df['churn'] == True)]

  customer  age  plan  monthly_spend  churn
0        A   22  Free              0      1
3        D   41  Free              0      1
5        F   38  Free             10      1

In [ ]:
df[['age']].mean()

age    31.666667
dtype: float64

In [ ]:
df[['monthly_spend']].mean()

monthly_spend    28.333333
dtype: float64

In [ ]:
(df["churn"] == True).sum() /len(df) *100

np.float64(50.0)

In [ ]:
df.groupby("plan")['monthly_spend'].mean()

plan
Free     3.333333
Pro     53.333333
Name: monthly_spend, dtype: float64

In [ ]:
df.groupby("plan")['monthly_spend'].count()

plan
Free    3
Pro     3
Name: monthly_spend, dtype: int64

In [ ]:
df.groupby("plan")['monthly_spend'].agg(["count","mean","sum"])

      count       mean  sum
plan
Free      3   3.333333   10
Pro       3  53.333333  160

In [ ]:
from numpy import mean
df.groupby("plan").agg(
    average_age=("age", "mean" ),
    average_spend= ("monthly_spend", "mean"),
    churn_rate = ("churn", "mean")
)

      average_age  average_spend  churn_rate
plan
Free    33.666667       3.333333         1.0
Pro     29.666667      53.333333         0.0

In [ ]:
df.groupby("plan").size()

plan
Free    3
Pro     3
dtype: int64

In [ ]:
df.groupby("plan")["monthly_spend"].count()

plan
Free    3
Pro     3
Name: monthly_spend, dtype: int64

In [ ]:
df["plan"].value_counts()

plan
Free    3
Pro     3
Name: count, dtype: int64

In [ ]:
df["plan"].value_counts(normalize=True)

plan
Free    0.5
Pro     0.5
Name: proportion, dtype: float64

In [ ]:
df.groupby("plan")["customer"].count()

plan
Free    3
Pro     3
Name: customer, dtype: int64

In [ ]:
df.groupby("plan")["monthly_spend"].mean()

plan
Free     3.333333
Pro     53.333333
Name: monthly_spend, dtype: float64

In [ ]:
df.groupby("plan")["monthly_spend"].count()

plan
Free    3
Pro     3
Name: monthly_spend, dtype: int64

In [ ]:
df.groupby("plan")["churn"].mean()

plan
Free    1.0
Pro     0.0
Name: churn, dtype: float64

In [ ]:
df.columns

Index(['customer', 'age', 'plan', 'monthly_spend', 'churn'], dtype='object')

In [ ]:
df.groupby("plan").agg(
    customer_count = ("customer","count"),
    average_age = ("age","mean"),
    average_spend = ("monthly_spend","mean"),
    churn_rate = ("churn","mean")
)

      customer_count  average_age  average_spend  churn_rate
plan
Free               3    33.666667       3.333333         1.0
Pro                3    29.666667      53.333333         0.0

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Hina"],
    "age": [25, None, 29, 27],
    "spend": [50, 40, None, 70],
})

In [ ]:
df.isna()

    name    age  spend
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [ ]:
df.isna().sum()

name     0
age      1
spend    1
dtype: int64

In [ ]:
df.isna().mean() * 100

name      0.0
age      25.0
spend    25.0
dtype: float64

In [ ]:
df[df.isna().any(axis=1)]

    name   age  spend
1   Sara   NaN   40.0
2  Ahmed  29.0    NaN

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

In [ ]:
df = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [25, None, 31, 28, None],
    "income": [50000, 60000, None, 55000, 52000],
    "plan": ["Pro", "Free", None, "Pro", "Free"]
})

In [ ]:
df.isna().sum()

customer    0
age         2
income      1
plan        1
dtype: int64

In [ ]:
df.isna().mean() *100

customer     0.0
age         40.0
income      20.0
plan        20.0
dtype: float64

In [ ]:
df.isna()

   customer    age  income   plan
0     False  False   False  False
1     False   True   False  False
2     False  False    True   True
3     False  False   False  False
4     False   True   False  False

In [ ]:
df[df.isna().any(axis=1)]

  customer   age   income  plan
1        B   NaN  60000.0  Free
2        C  31.0      NaN  None
4        E   NaN  52000.0  Free

In [ ]:
df['age']

0    25.0
1     NaN
2    31.0
3    28.0
4     NaN
Name: age, dtype: float64

In [ ]:
df['age'] = df['age'].fillna(df['age'].mean())

In [ ]:
df['age']

0    25.0
1    28.0
2    31.0
3    28.0
4    28.0
Name: age, dtype: float64

In [ ]:
df['income']

0    50000.0
1    60000.0
2        NaN
3    55000.0
4    52000.0
Name: income, dtype: float64

In [ ]:
df['income'] = df['income'].fillna(df['income'].median())

In [ ]:
df['income']

0    50000.0
1    60000.0
2    53500.0
3    55000.0
4    52000.0
Name: income, dtype: float64

In [ ]:
df

  customer   age   income  plan
0        A  25.0  50000.0   Pro
1        B  28.0  60000.0  Free
2        C  31.0  53500.0  None
3        D  28.0  55000.0   Pro
4        E  28.0  52000.0  Free

In [ ]:

customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Ali", "Sara", "Ahmed"],
    "plan": ["Pro", "Free", "Pro"]
})

orders = pd.DataFrame({
    "customer_id": [1, 1, 3],
    "order_id": ["O101", "O102", "O103"],
    "amount": [500, 300, 700]
})

In [ ]:
merged = customers.merge(orders, on="customer_id", how="inner")
print(merged)

   customer_id   name plan order_id  amount
0            1    Ali  Pro     O101     500
1            1    Ali  Pro     O102     300
2            3  Ahmed  Pro     O103     700

In [ ]:
merged = customers.merge(orders, on="customer_id", how="left")
print(merged)

   customer_id   name  plan order_id  amount
0            1    Ali   Pro     O101   500.0
1            1    Ali   Pro     O102   300.0
2            2   Sara  Free      NaN     NaN
3            3  Ahmed   Pro     O103   700.0

In [ ]:
merged = customers.merge(orders, on="customer_id", how="right")
print(merged)

   customer_id   name plan order_id  amount
0            1    Ali  Pro     O101     500
1            1    Ali  Pro     O102     300
2            3  Ahmed  Pro     O103     700

In [ ]:
merged = customers.merge(orders, on="customer_id", how="outer")
print(merged)

   customer_id   name  plan order_id  amount
0            1    Ali   Pro     O101   500.0
1            1    Ali   Pro     O102   300.0
2            2   Sara  Free      NaN     NaN
3            3  Ahmed   Pro     O103   700.0

In [ ]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Ali", "Sara", "Ahmed"]
})

orders = pd.DataFrame({
    "user_id": [1, 1, 3],
    "amount": [500, 300, 700]
})

In [ ]:
merged = customers.merge(orders, left_on="customer_id", right_on="user_id", how="inner")
print(merged)

   customer_id   name  user_id  amount
0            1    Ali        1     500
1            1    Ali        1     300
2            3  Ahmed        3     700

In [ ]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Ali", "Sara", "Ahmed", "Hina"],
    "plan": ["Pro", "Free", "Pro", "Free"]
})

orders = pd.DataFrame({
    "customer_id": [1, 1, 3, 5],
    "order_id": ["O101", "O102", "O103", "O104"],
    "amount": [500, 300, 700, 200]
})

In [ ]:
merged_df = customers.merge(orders, on="customer_id", how="left")
print(merged_df)

   customer_id   name  plan order_id  amount
0            1    Ali   Pro     O101   500.0
1            1    Ali   Pro     O102   300.0
2            2   Sara  Free      NaN     NaN
3            3  Ahmed   Pro     O103   700.0
4            4   Hina  Free      NaN     NaN

In [ ]:
nan_rows = merged_df[merged_df['order_id'].isna()]
print(nan_rows)

   customer_id  name  plan order_id  amount
2            2  Sara  Free      NaN     NaN
4            4  Hina  Free      NaN     NaN

In [ ]:
merged_df = customers.merge(orders, on="customer_id", how="right")
print(merged_df)

   customer_id   name plan order_id  amount
0            1    Ali  Pro     O101     500
1            1    Ali  Pro     O102     300
2            3  Ahmed  Pro     O103     700
3            5    NaN  NaN     O104     200

In [ ]:
nan_rows = merged_df[merged_df['customer_id'].isna()]
print(nan_rows)

Empty DataFrame
Columns: [customer_id, name, plan, order_id, amount]
Index: []

In [ ]:
# 1. Right join keeps everything from the orders table
right_merged = customers.merge(orders, on="customer_id", how="right")

# 2. Filter where customers table columns (like customer_name or email) are NaN
orders_only = right_merged[right_merged['customer_name'].isna()]

print(orders_only['customer_id'].unique())

KeyError: 'customer_name'